In [ ]:
import numpy as np
arr_1d = np.array([1,2,3,4,6])
print("1d array", arr_1d)

arr_2d = np.array([[1,2,3],[4,5,6]])
print("2d array", arr_2d)

1d array [1 2 3 4 6]
2d array [[1 2 3]
 [4 5 6]]


#### list vs numpy array


In [ ]:
py_list = [1,2,3]
print("Python List Multiplication", py_list * 2)


np_array = np.array([1,2,3]) #element wise multiplications
print("Python List Multiplication", np_array * 2)

import time
start = time.time()
py_list = [i*2 for i in range(1000000)]
print("\n List operation time : ", time.time() - start)


start = time.time()
np_array = np.arange(1000000)
print("\n List operation time : ", time.time() - start)

Python List Multiplication [1, 2, 3, 1, 2, 3]
Python List Multiplication [2 4 6]

 List operation time :  0.3595561981201172

 List operation time :  0.012666940689086914


###creating arrays from scratch


In [10]:
zeros = np.zeros((3,4))

print("zeros array: \n", zeros)

once = np.ones((2,3))

print("once array: \n", once)

full = np.full((2,3), 7)

print("full array: \n", full)

random = np.random.random((2,3))


print("random array: \n", random)


seqence = np.arange(0, 11, 2)

print("seqence array: \n", seqence)

zeros array: 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
once array: 
 [[1. 1. 1.]
 [1. 1. 1.]]
full array: 
 [[7 7 7]
 [7 7 7]]
random array: 
 [[0.63952505 0.42102769 0.39492739]
 [0.70436309 0.65377639 0.48994001]]
seqence array: 
 [ 0  2  4  6  8 10]


### Vector, Matrix and Tensor

In [11]:
vector = np.array([1,2,3])
print("vector", vector)

matrix = np.array([[1,2,3],[3,4,5]])

print("matrix", matrix)

tensor = np.array([[[1,2],[3,4]], [[5,6],[7,8]]])
print("tensor", tensor)


vector [1 2 3]
matrix [[1 2 3]
 [3 4 5]]
tensor [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


### Array propertis

In [12]:
arr = np.array([[1,2,3],[4,5,6]])

print("shapes of array", arr.shape)
print("Dimension", arr.ndim)
print("Size", arr.size)
print("Datatypee", arr.dtype)


shapes of array (2, 3)
Dimension 2
Size 6
Datatypee int64


### Array reshape


In [ ]:
ar = np.arange(0,12)
print("orignal array: \n", ar)

resahped = ar.reshape((3,4))
print(" \n reshaped array: \n", resahped)


flattened = resahped.flatten()
print('\n flattened array', flattened)

raveled = resahped.ravel()
# returned view, insted of copy
print("raveled array", raveled)


#transpose
transpose = resahped.T

print("transpose", transpose)

orignal array: 
 [ 0  1  2  3  4  5  6  7  8  9 10 11]
 
 reshaped array: 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

 flattened array [ 0  1  2  3  4  5  6  7  8  9 10 11]
raveled array [ 0  1  2  3  4  5  6  7  8  9 10 11]
transpose [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
