### Numpy array Operations

In [4]:
import numpy as np

In [5]:
arr = np.array([1,2,3,4,5,6,7,8,9])
print("Basic Slicing:", arr[2:7])
print("with stp:", arr[1:8:2])
print("neatie indexing:", arr[-3])



Basic Slicing: [3 4 5 6 7]
with stp: [2 4 6 8]
neatie indexing: 7


In [6]:
arr_2d =  np.array([[1,2,3],
                    [4,5,6],
                    [7,8,9]])

print("specific element", arr_2d[1,2])
print("entrre row", arr_2d[1])
print("entrre row", arr_2d[:, 1])

specific element 6
entrre row [4 5 6]
entrre row [2 5 8]


### sorting


In [34]:
unsorted = np.array([3,1,1,4,5,9,2,6])
print(np.sort(unsorted))

arr_2d_unsorted = np.array([[3,1],[1,2],[2,3]])
print("sorted 2d array by colom", np.sort(arr_2d_unsorted,axis=1))

[1 1 2 3 4 5 6 9]
sorted 2d array by colom [[1 3]
 [1 2]
 [2 3]]


### Filtering

In [8]:
numbers = np.array([1,2,3,4,5,6,7,8,9,10])

even_number = numbers[ numbers % 2 == 0 ]

print(even_number)

[ 2  4  6  8 10]


# filter with mask


In [9]:
mask = numbers > 5
print("numbers greater than 5",numbers[mask])

numbers greater than 5 [ 6  7  8  9 10]


### Fancy index vs np.where()

In [12]:
indices = [0,1,2]
print(numbers[indices])


where_result = np.where(numbers > 5)

print("where results", numbers[where_result])

[1 2 3]
where results [ 6  7  8  9 10]


In [35]:
condition_arr = np.where(numbers > 5, numbers*2, numbers)
print(condition_arr)

[ 1  2  3  4  5 12 14 16 18 20]


### add and remve data


In [ ]:
arr = np.array([1,2,3])
arr2 = np.array([4,5,6])

combined = arr + arr2
print(combined)

concating = np.concatenate((arr, arr2))

print(concating)

[5 7 9]
[1 2 3 4 5 6]


### array compability


In [ ]:
a = np.array([1,2,3])
b = np.array([4,5,6, 7])
c = np.array([7,8,9])


print("compatibilty shape:", a.shape == b.shape)



compatibilty shape: False


In [31]:
original = np.array([[1,2], [3,4]])
new_row = np.array([[5,6]])

with_new_row = np.vstack((original, new_row))
print("orignal", original)

print("vstack", with_new_row)

new_colm = np.array([[7],[8]])
with_new_col = np.hstack((original, new_colm))

print("new_colm to add",new_colm)

print("nre with col", with_new_col)

orignal [[1 2]
 [3 4]]
vstack [[1 2]
 [3 4]
 [5 6]]
new_colm to add [[7]
 [8]]
nre with col [[1 2 7]
 [3 4 8]]


In [38]:
arr = np.array([1,2,3,4,5])
deleted_var = np.delete(arr, 2) # new_Array return
print("ArrAY AFTER DELETETION",deleted_var)
deleted_var = np.delete(deleted_var, 2) # new_Array return
print("ArrAY AFTER DELETETION",deleted_var,"2")
print(deleted_var)

ArrAY AFTER DELETETION [1 2 4 5]
ArrAY AFTER DELETETION [1 2 5] 2
[1 2 5]


###